apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- backend-svc.yaml
- backend-v0-dep.yaml
- backend-v1-dep.yaml
- backend-v2-dep.yaml
- frontend-dep.yaml
- frontend-svc.yaml
- ingress-frontend.yaml
- namespace.yaml
- postgres-master-dep.yaml
- postgres-master-svc.yaml
- redis-master-dep.yaml
- redis-master-svc.yaml
